### ISSUE TITLE
NpgsqlDbType not correctly set on insert | bytea instead of geometry | NHibernate v8.0.0

### ISSUE THREAD

**Issue by martinhorvath** [nhibernate/NHibernate.Spatial#140]
Hello folks,

my apologies if I don't follow your standard conventions for not known. Just pm me and I'm correcting the things I've done wrong.

### What's wrong?
The correct npgsqltype (NpgsqlTypes.NpgsqlDbType.Geometry) is not set on the parameter. It's bytea instead.
`System.InvalidCastException: Writing values of 'NetTopologySuite.Geometries.Point' is not supported for parameters having NpgsqlDbType 'Bytea'.`

### What I'm doing
`_session.Save(position)`

Position is mapped as follows:
```
public PositionMap() {
       Schema("airtime");
      Table("position");
       Id(x => x.Id).GeneratedBy.Assigned();
        Map(x => x.Geom) //NetTopologySuite.Geometries.Point
           .CustomType<CustomPostGisGeometryType>();
}
```

This all worked fine with the following libs (now I am on 8.0.0):
```
<PackageReference Include="FluentNHibernate" Version="3.1.0" />
<PackageReference Include="NetTopologySuite" Version="2.1.0" />
<PackageReference Include="NHibernate.Spatial" Version="6.0.0" />
<PackageReference Include="NHibernate.Spatial.PostGis" Version="6.0.0" />
<PackageReference Include="Npgsql" Version="3.2.7" />
<PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
```

### What I did to locate the issue
I've created a custom NpgSqlDriver and a custom mapping type:

`class CustomPostGisGeometryType : GeometryTypeBase<Geometry>`
`class CustomNpgSqlDriver : NpgsqlDriver`

On transaction commit, the code reaches the following places in this order:
       1. CustomNpgSqlDriver.GenerateCommand(CommandType type, SqlString sqlString, SqlType[] parameterTypes)
       2. CustomNpgSqlDriver.InitializeParameter(DbParameter dbParam, string name, SqlType sqlType)
       3. CustomPostGisGeometryType.Set(DbCommand cmd, object value, int index, ISessionImplementor session)
       5. CustomNpgSqlDriver.GenerateCommand(CommandType type, SqlString sqlString, SqlType[] parameterTypes)
       6. CustomNpgSqlDriver.InitializeParameter(DbParameter dbParam, string name, SqlType sqlType)
       7. It's not reaching the CustomPostGisGeometryType Set-Method and then crashes with below stack trace.

```
System.InvalidCastException: Writing values of 'NetTopologySuite.Geometries.Point' is not supported for parameters having NpgsqlDbType 'Bytea'.
at Npgsql.Internal.AdoSerializerHelpers.<GetTypeInfoForWriting>g__ThrowWritingNotSupported|1_0(Type type, PgSerializerOptions options, Nullable1 pgTypeId, Nullable1 npgsqlDbType, Exception inner)
   at Npgsql.Internal.AdoSerializerHelpers.GetTypeInfoForWriting(Type type, Nullable`1 pgTypeId, PgSerializerOptions options, Nullable1 npgsqlDbType)
   at Npgsql.NpgsqlParameter.ResolveTypeInfo(PgSerializerOptions options)
   at Npgsql.NpgsqlParameterCollection.ProcessParameters(PgSerializerOptions options, Boolean validateValues, CommandType commandType)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.GenericBatchingBatcher.BatchingCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.GenericBatchingBatcher.DoExecuteBatch(DbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(DbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   at NHibernate.Engine.ActionQueue.ExecuteActions[T](List1 list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
   at NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   at NHibernate.Impl.SessionImpl.Flush()
   at NHibernate.Impl.SessionImpl.FlushBeforeTransactionCompletion()
   at NHibernate.Impl.SessionImpl.BeforeTransactionCompletion(ITransaction tx)
   at NHibernate.Transaction.AdoTransaction.Commit()
```
Can anyone help me out or point me into the right direction?

Best regards,
Martin

**Comment by martinhorvath** [comment]
Hi @peetw, I used a custom type and a custom npgsql driver just to debug into this piece deeper. I just did a really quick and dirty copy and paste out of my project and fed this repo: https://github.com/martinhorvath/nhibernatespatialtest

Just call the "test" endpoint... db-params go into launch.json (sample in repo).

One could get this error-free by break-pointing into CustomNpgSqlDriver line 18 and overriding parameter :p3 with the two lines inside the if clause.

Let me know if you need more :-)

**Comment by peetw** [comment]
Thanks for that. The root cause of the issue was the addition of `.AdoNetBatchSize(20)` to the NHibernate configuration on [L:39](https://github.com/martinhorvath/nhibernatespatialtest/blob/cb5810c0a2d0655905e98e5ef1bbb77f5dd8718c/RDBMS.cs#L39).

If you remove that it resolves the type mapping issue. However, you will also need to update the `Npgsql.NetTopologySuite` NuGet package to be the same version as the `Npgsql` NuGet package and then uncomment the `NpgsqlConnection.GlobalTypeMapper.UseNetTopologySuite();` line. Once done, the example then works as expected.
