### ISSUE TITLE
Fetching large geometries gets OutOfMemoryException

### ISSUE THREAD

**Issue by keyjote** [nhibernate/NHibernate.Spatial#30]
When testing most of the time seems to work, but for large geometries I got an exception:

```
2016-02-17 18:19:15,645 [40] WARN  NHibernate.Util.ADOExceptionReporter [(null)] - System.OutOfMemoryException: Array dimensions exceeded supported range.
   at NHibernate.Spatial.Type.PostGisGeometryType.ToString(Byte[] bytes)
   at NHibernate.Spatial.Type.GeometryTypeBase`1.DeepCopy(Object value)
   at NHibernate.Type.TypeHelper.DeepCopy(Object[] values, IType[] types, Boolean[] copy, Object[] target, ISessionImplementor session)
   at NHibernate.Engine.TwoPhaseLoad.InitializeEntity(Object entity, Boolean readOnly, ISessionImplementor session, PreLoadEvent preLoadEvent, PostLoadEvent postLoadEvent)
   at NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, Object resultSetId, ISessionImplementor session, Boolean readOnly)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.LoadCollection(ISessionImplementor session, Object id, IType type)
```

I am using postgres/postgis, running NHibernate version 4.0.4.4000 and NHibernate.Spatial.PostGis 4.0.4.4000.

my geometry in the db is not that big, it has 5104 points, which is 83672 bytes (82 kB).
Is there a limit on geometries? how can I handle big ones? 
My system should support even bigger ones, the biggest I have at the moment is about 1664kB.

Any ideas?

**Comment by andrerav** [comment]
Hi @keyjote. I will need to debug this. Can you please provide your mapping configuration and an SQL script which creates a table and populates it with the data that triggers the crash?

**Comment by andrerav** [comment]
@keyjote I suggest that we try to solve issue #31 before taking a closer look at this problem.

**Comment by keyjote** [comment]
@andrerav aha! ok, no worries, but I will still add a script file so you can reproduce a big geometry. Not pressuring you, I will just do it so I don't forget about it.

**Comment by andrerav** [comment]
@keyjote That's great, thanks! :)

**Comment by peetw** [comment]
I too also encountered this bug recently.

The issue is actually caused by a [bug](https://github.com/NetTopologySuite/NetTopologySuite/issues/100) in the PostGisWriter class (from NetTopologySuite) that causes it to overestimate the size in bytes for polygons. The bug has been [fixed](https://github.com/NetTopologySuite/NetTopologySuite/pull/101) in NTS 1.15-pre, which [can be assumed to be stable](https://github.com/NetTopologySuite/NetTopologySuite/issues/94).

**Comment by andrerav** [comment]
I will put out a pre version of NHib.Spatial on Nuget built for NTS 1.15.
Thanks @peetw!
